// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAXnXdJuvBQXskrxEGq5N22eSW893PQ9A',
    appId: '1:585628951223:web:9c192a067ea999bd19e332',
    messagingSenderId: '585628951223',
    projectId: 'chatapp-28cfd',
    authDomain: 'chatapp-28cfd.firebaseapp.com',
    storageBucket: 'chatapp-28cfd.firebasestorage.app',
    measurementId: 'G-S62FX2PNYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAup4jinsM8HQ-bXcq69deDLp70v5zJgUI',
    appId: '1:585628951223:android:02bc3f8f3464b92419e332',
    messagingSenderId: '585628951223',
    projectId: 'chatapp-28cfd',
    storageBucket: 'chatapp-28cfd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTYdaYpzbSA6mKxW8zYGZ7sjaSowUsdVo',
    appId: '1:585628951223:ios:965dda51879a170819e332',
    messagingSenderId: '585628951223',
    projectId: 'chatapp-28cfd',
    storageBucket: 'chatapp-28cfd.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTYdaYpzbSA6mKxW8zYGZ7sjaSowUsdVo',
    appId: '1:585628951223:ios:965dda51879a170819e332',
    messagingSenderId: '585628951223',
    projectId: 'chatapp-28cfd',
    storageBucket: 'chatapp-28cfd.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAXnXdJuvBQXskrxEGq5N22eSW893PQ9A',
    appId: '1:585628951223:web:85a0f7301f1b637c19e332',
    messagingSenderId: '585628951223',
    projectId: 'chatapp-28cfd',
    authDomain: 'chatapp-28cfd.firebaseapp.com',
    storageBucket: 'chatapp-28cfd.firebasestorage.app',
    measurementId: 'G-S078S02H18',
  );
}
